// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }
// src/app/layout.tsx
// Layout position: Root layout — wraps the entire application.
// Server Component — no "use client" needed. Fonts loaded once here,
// injected as CSS custom properties consumed by globals.css @theme.

// -----------------------------------------------

// import type { Metadata } from "next";
// import { Geist, Geist_Mono, Noto_Naskh_Arabic } from "next/font/google";
// import "./globals.css";
// import { ThemeProvider } from "@/lib/theme/theme-provider";

// const geist = Geist({
//   variable: "--font-geist", // ← must match globals.css: var(--font-geist)
//   subsets: ["latin"],
//   display: "swap",
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono", // ← must match globals.css: var(--font-geist-mono)
//   subsets: ["latin"],
//   display: "swap",
// });

// const notoNaskhArabic = Noto_Naskh_Arabic({
//   variable: "--font-noto-naskh", // ← must match globals.css: var(--font-noto-naskh)
//   subsets: ["arabic"],
//   weight: ["400", "500", "600", "700"],
//   display: "swap",
// });

// export const metadata: Metadata = {
//   title: {
//     template: "%s — Portfolio",
//     default: "Full-Stack Engineer — Portfolio",
//   },
//   description:
//     "Full-Stack Engineer specializing in Next.js, Node.js, and scalable web systems.",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{ children: React.ReactNode }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geist.variable} ${geistMono.variable} ${notoNaskhArabic.variable}`}
//       suppressHydrationWarning
//     >
//       <body className="min-h-dvh flex flex-col">
//         <ThemeProvider
//           attribute="class"
//           defaultTheme="system"
//           enableSystem
//           disableTransitionOnChange={false}
//           storageKey="portfolio-theme"
//         >
//           {children}
//         </ThemeProvider>
//       </body>
//     </html>
//   );
// }

// --------------------------------
// Locale layout — wraps every page within a locale segment.
// Server Component — no "use client".
//
// Responsibilities:
//   1. Await params (Next.js 15 — params is a Promise)
//   2. Validate locale
//   3. Set lang + dir on <html>
//   4. Provide next-intl messages to the tree
//   5. Wrap with ThemeProvider

import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import { getMessages, getTranslations } from "next-intl/server";
import { Geist, Geist_Mono, Noto_Naskh_Arabic } from "next/font/google";
import { ThemeProvider } from "@/lib/theme/theme-provider";
import { routing, type Locale, type LocaleParams } from "@/temp/i18n/routing";
import "@/app/globals.css";

// ── Fonts ─────────────────────────────────────────────────────────────────────
// Variables injected on <html> as CSS custom properties.
// globals.css @theme block references these via var(--font-geist) etc.

const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
  display: "swap",
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

const notoNaskhArabic = Noto_Naskh_Arabic({
  variable: "--font-noto-naskh",
  subsets: ["arabic"],
  weight: ["400", "500", "600", "700"],
  display: "swap",
});

// ── Metadata ──────────────────────────────────────────────────────────────────
export async function generateMetadata({
  params,
}: {
  params: Promise<LocaleParams>;
}): Promise<Metadata> {
  const { locale } = await params;
  const t = await getTranslations({ locale, namespace: "Meta" });

  return {
    title: {
      template: "%s — Portfolio",
      default: t("defaultTitle"),
    },
    description: t("description"),
    metadataBase: new URL(
      process.env.NEXT_PUBLIC_BASE_URL ?? "http://localhost:3000",
    ),
  };
}

// ── Static params — tells Next.js which locale segments to pre-render ─────────
export function generateStaticParams(): LocaleParams[] {
  return routing.locales.map((locale) => ({ locale }));
}

// ── Layout ────────────────────────────────────────────────────────────────────
export default async function LocaleLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: Promise<LocaleParams>;
}) {
  const { locale } = await params;

  // Guard: redirect to 404 if locale is not in our defined list.
  // This handles direct URL manipulation like /fr/... or /xyz/...
  if (!routing.locales.includes(locale)) {
    notFound();
  }

  const messages = await getMessages();
  const dir = locale === "ar" ? "rtl" : "ltr";

  return (
    <html
      lang={locale}
      dir={dir}
      suppressHydrationWarning
      className={`${geist.variable} ${geistMono.variable} ${notoNaskhArabic.variable}`}
    >
      <body className="min-h-dvh flex flex-col bg-background text-foreground transition-theme">
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange={false}
          storageKey="portfolio-theme"
        >
          <NextIntlClientProvider messages={messages}>
            {/* Skip to main content — accessibility */}
            <a
              href="#main-content"
              className="sr-only focus:not-sr-only focus:fixed focus:inset-s-4 focus:top-4 focus:z-50 focus:bg-card focus:px-4 focus:py-2 focus:text-foreground focus:border focus:border-border"
            >
              {locale === "ar" ? "الانتقال إلى المحتوى" : "Skip to content"}
            </a>
            {children}
          </NextIntlClientProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
